defaults:
  - model: wangchanberta/config
  - labels: test1/labels
  - memory_replay: test1-replay-path

_version_: null
_preset_id_: null

versioning_config:
  prefix: prefix_
  version_number: 0.0
  backup_version_config: True
  version_config_path: C:/Users/patom/OneDrive/Documents/Repo/LittleConfig/LittleConfig/test/version-configs

project_config:
  name: ml-test1
  path: C:/Users/patom/OneDrive/Documents/Repo/LittleConfig/LittleConfig/test/projects

mode: train # train, test, fine-tune, transfer
method: memory-replay # memory-replay, non-memory-replay

data_config:
  feature_columns: text

training_config:
  epochs: 10
  patience: 3
  batch_size: 64
  val_size: 0.2
  test_size: 0.1
  lr: 2e-5
  weight_decay_rate_0: 0.01
  weight_decay_rate_1: 0.0
  max_length: 200
  random_state: 888