
defaults:
  - models: wangchanberta/model-config
  - converter: 
  - parameters: default-parameters-config
  - mapper: Sunflower/next/spam-detection/labels-mapper
  - memory_replay: Sunflower/next/spam-detection/replay-config-for-test
  - _self_

problem_type: multi_label_classification

mode: train # train, test, fine-tune, transfer
method: memory-replay # memory-replay, non-memory-replay

title: next-spam-detection # e.g. level2_transfer
version: v0.1a_vscode # e.g. v2.1.1_PATCH
text_col: pre_text

model_path: workflow/pretrained/spam-detection
#checkpoint_path: workflow/pretrained/spam-detection/next-spam-detection_model_v4.4d_typhoon/checkpoints/

epochs: 1000
patience: 5
batch_size: 64
ratio:
  val_size: 0.2
  test_size: 0.1

datasets:
  train_path: 
  validation_path: 
  test_path: 

train:
  save_best_model_path: workflow/pretrained/spam-detection/next-survey_model_v0.1a_vscode/

test:
  from_pretrained_path: workflow/pretrained/spam-detection/next-spam-detection_model_v0.1a_vscode/pretrained
  clf_report_path: workflow/pretrained/spam-detection/next-spam-detection_model_v0.1a_vscode/

fine_tune:
  from_pretrained_path: workflow/pretrained/spam-detection/next-spam-detection_model_v0.1a_vscode/pretrained
  save_best_model_path: workflow/pretrained/spam-detection/next-spam-detection_model_v0.1a_vscode/

transfer:
  from_pretrained_path: </path/to/model/pretrained> # Override this
  save_best_model_path: workflow/pretrained/spam-detection/next-spam-detection_model_v0.1a_vscode/

#### THIS CONFIG FILE WAS GENERATED BY CONFIG GENERATOR ####
